name: Test Compilation for OCaml

on: [pull_request]

# Prevent parallel CI: Stop every workflow of a branch
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install OCaml
        uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.0
          opam-repositories: |
            rocq-released: https://rocq-prover.org/opam/released
            default: https://github.com/ocaml/opam-repository.git

      - name: Install Rocq and Iris
        run: opam install . --deps-only -y

      - name: Build
        run: |
            opam exec -- dune build --display short
