name: Test Compilation for OCaml

on: [ pull_request ]
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install OCaml
        uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.0
          opam-repositories: |
            rocq-released: https://rocq-prover.org/opam/released
            default: https://github.com/ocaml/opam-repository.git
          dune-cache: true

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: _opam
          key: ${{ runner.os }}-opam-${{ hashFiles('*.opam.locked') }}
          restore-keys: |
            ${{ runner.os }}-opam-

      - name: Cache Dune
        uses: actions/cache@v4
        with:
          path: ~/.cache/dune
          key: ${{ runner.os }}-dune-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dune-

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Rocq and Iris
        run: opam install . --deps-only -y

      - name: Build
        run: |
            opam exec -- dune build --display short -j2
