name: Test Compilation for OCaml

# Prevent parallel CI: Stop every workflow of a branch
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

on: [ pull_request ]
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    env:
      OCAML_VERSION: "5.4.0"
      JOBS_LIMIT: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install OCaml
        uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ env.OCAML_VERSION }}
          opam-repositories: |
            rocq-released: https://rocq-prover.org/opam/released
            default: https://github.com/ocaml/opam-repository.git
          dune-cache: true

      - name: Cache opam
        id: restore-opam
        uses: actions/cache@v4
        with:
          path: ${{ env.OPAMROOT }}
          key: |
            opam-${{ runner.os }}-ocaml${{ env.OCAML_VERSION }}-${{ hashFiles('*.opam.locked') }}
          restore-keys: |
            opam-${{ runner.os }}-ocaml${{ env.OCAML_VERSION }}-

      - name: Install Rocq and Iris (deps only)
        run: |
          eval "$(opam env)"
          opam install . --deps-only -y

      - name: Cache Dune _build directory
        id: cache-build
        uses: actions/cache@v4
        with:
          path: _build
          key: |
            dune-build-${{ runner.os }}-ocaml${{ env.OCAML_VERSION }}-${{ hashFiles('*.opam.locked', 'dune-project') }}
          restore-keys: |
            dune-build-${{ runner.os }}-ocaml${{ env.OCAML_VERSION }}-

      - name: Build
        run: |
          eval "$(opam env)"
          opam exec -- dune build --display short -j ${{ env.JOBS_LIMIT }}
